// <auto-generated />
using ConsoleApp62.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConsoleApp62.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20210921064307_Ver1")]
    partial class Ver1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ConsoleApp62.DB.Model.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeCarId")
                        .HasColumnType("int");

                    b.HasKey("CarId");

                    b.HasIndex("TypeCarId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("ConsoleApp62.DB.Model.TypeCar", b =>
                {
                    b.Property<int>("TypeCarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TypeCarId");

                    b.ToTable("TypeCars");
                });

            modelBuilder.Entity("ConsoleApp62.DB.Model.Car", b =>
                {
                    b.HasOne("ConsoleApp62.DB.Model.TypeCar", "TypeCar")
                        .WithMany()
                        .HasForeignKey("TypeCarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeCar");
                });
#pragma warning restore 612, 618
        }
    }
}
